version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
